#!/bin/bash

docker network rm bosagora_network
docker network create --subnet=172.200.0.0/16 bosagora_network

./agora/script.sh stop-agora-scan
sleep 2

./agora/script.sh stop-boa-scan
sleep 2

./agora/script.sh stop-db
sleep 2

./agora/script.sh stop
sleep 2

./agora/script.sh start-db
sleep 5

./agora/script.sh init-db
sleep 5

./agora/script.sh init

echo "[Step 1]"

cp -f agora/nodes-capella/steps/docker-compose-step1.yml agora/nodes-capella/docker-compose.yml
docker-compose -f "$(pwd)"/agora/nodes-capella/docker-compose.yml up -d

sleep 5

while true; do
  case "$1" in
    -b|--boascan)
      ./agora/script.sh start-boa-scan
      break;;
     *)
      break;;
  esac
done

sleep 5

npm run deploy:commons_budeget
npm run deploy:deposit
npm run staking

./agora/script.sh start-agora-scan


function change_step() {
  # Fork Shang-hai & Capella
  docker stop node"$2"-3-val
  docker rm node"$2"-3-val
  docker stop node"$2"-2-cl
  docker rm node"$2"-2-cl
  docker stop node"$2"-1-el
  docker rm node"$2"-1-el

  cp -f agora/nodes-capella/steps/docker-compose-step"$1".yml agora/nodes-capella/docker-compose.yml

  docker run -it \
  -v "$(pwd)"/agora/chain/node"$2"/el:/data \
  -v "$(pwd)"/agora/config/el:/config \
  --name el-node --rm bosagora/agora-el-node:agora_v1.11.6-b360ab \
  --datadir=/data init /config/genesis-shanghai.json

  docker-compose -f "$(pwd)"/agora/nodes-capella/docker-compose.yml up -d node"$2"-1-el
  docker-compose -f "$(pwd)"/agora/nodes-capella/docker-compose.yml up -d node"$2"-2-cl
  docker-compose -f "$(pwd)"/agora/nodes-capella/docker-compose.yml up -d node"$2"-3-val
}

npx hardhat wait-block --title "Step 1, (GENESIS + 0)" --fork GENESIS --offset 0 --network localhost

npx hardhat wait-block --title "Step 1, (BELLATRIX + 0)" --fork BELLATRIX --offset 0 --network localhost

# Step 2
npx hardhat wait-block --title "Step 2, (BELLATRIX + 35)" --fork BELLATRIX --offset 35 --network localhost
change_step 2 5

# Step 3
npx hardhat wait-block --title "Step 3, (BELLATRIX + 50)" --fork BELLATRIX --offset 50 --network localhost
change_step 3 4

# Step 4
npx hardhat wait-block --title "Step 4, (BELLATRIX + 65)" --fork BELLATRIX --offset 65 --network localhost
change_step 4 3

# Step 5
npx hardhat wait-block --title "Step 5, (BELLATRIX + 80)" --fork BELLATRIX --offset 80 --network localhost
change_step 5 2

# Step 6
npx hardhat wait-block --title "Step 6, (BELLATRIX + 95)" --fork BELLATRIX --offset 95 --network localhost
change_step 6 1

# Step 7
npx hardhat wait-block --title "Step 7, (CAPELLA + 0)" --fork CAPELLA --offset 0 --network localhost
