#!/bin/bash

./agora/script.sh stop-agora-scan
sleep 5

./agora/script.sh stop-db
sleep 5

./agora/script.sh stop
sleep 5

./agora/script.sh start-db
sleep 5

./agora/script.sh init-db
sleep 5

./agora/script.sh init

echo "[Step 1]"

cp -f agora/nodes-simulation/steps/docker-compose-step1.yml agora/nodes-simulation/docker-compose.yml
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d

sleep 5

npm run deploy:commons_budeget
npm run deploy:deposit
npm run staking

./agora/script.sh start-agora-scan


# Step 2
npx hardhat wait-block --title "Step 2" --fork BELLATRIX --offset 65 --network localhost

docker stop node4-3-val
docker rm node4-3-val
docker stop node4-2-cl
docker rm node4-2-cl
docker stop node4-1-el
docker rm node4-1-el
cp -f agora/nodes-simulation/steps/docker-compose-step2.yml agora/nodes-simulation/docker-compose.yml
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node4-1-el
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node4-2-cl
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node4-3-val


# Step 3
npx hardhat wait-block --title "Step 3" --fork BELLATRIX --offset 70 --network localhost

docker stop node3-3-val
docker rm node3-3-val
docker stop node3-2-cl
docker rm node3-2-cl
docker stop node3-1-el
docker rm node3-1-el
cp -f agora/nodes-simulation/steps/docker-compose-step3.yml agora/nodes-simulation/docker-compose.yml
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node3-1-el
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node3-2-cl
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node3-3-val


# Step 4
npx hardhat wait-block --title "Step 4" --fork BELLATRIX --offset 75 --network localhost

docker stop node2-3-val
docker rm node2-3-val
docker stop node2-2-cl
docker rm node2-2-cl
docker stop node2-1-el
docker rm node2-1-el
cp -f agora/nodes-simulation/steps/docker-compose-step4.yml agora/nodes-simulation/docker-compose.yml
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node2-1-el
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node2-2-cl
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node2-3-val


# Step 5
npx hardhat wait-block --title "Step 5" --fork BELLATRIX --offset 80 --network localhost

docker stop node1-3-val
docker rm node1-3-val
docker stop node1-2-cl
docker rm node1-2-cl
docker stop node1-1-el
docker rm node1-1-el
cp -f agora/nodes-simulation/steps/docker-compose-step5.yml agora/nodes-simulation/docker-compose.yml
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node1-1-el
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node1-2-cl
docker-compose -f $(pwd)/agora/nodes-simulation/docker-compose.yml up -d node1-3-val
