#!/bin/bash

docker network rm bosagora_network
docker network create --subnet=172.200.0.0/16 bosagora_network

./agora/cmd stop-agora-scan
sleep 2

./agora/cmd stop-boa-scan
sleep 2

./agora/cmd stop-db
sleep 2

./agora/cmd stop
sleep 2

./agora/cmd start-db
sleep 5

./agora/cmd init-db
sleep 5

./agora/cmd init

./agora/cmd start

sleep 5

npm run deploy:commons_budeget
npm run deploy:deposit
npm run staking

./agora/cmd start-agora-scan

sleep 5

while true; do
  case "$1" in
    -b|--boascan)
      ./agora/cmd start-boa-scan
      break;;
     *)
      break;;
  esac
done
