#!/bin/bash

if [[ -n $(docker-compose ls | grep "devnet") ]]
then
  ./agora-chain-ctrl/cmd.sh stop
fi

if [[ -n $(docker-compose ls | grep "agora-scan ") ]]
then
  ./agora/cmd.sh stop-agora-scan
fi

if [[ -n $(docker-compose ls | grep "boa-scan") ]]
then
  ./agora/cmd.sh stop-boa-scan
fi

if [[ -n $(docker-compose ls | grep "postgres") ]]
then
  ./agora/cmd.sh stop-db
fi

if [[ -n $(docker-compose ls | grep "nodes-bellatrix\|nodes-capella") ]]
then
  ./agora/cmd.sh stop
fi

if [[ -n $(docker network ls | grep "bosagora_network") ]]
then
  docker network rm bosagora_network
fi
