version: '3.3'
services:
  agorascan:
    image: bosagora/agora-scan:agora-v1.0.0
    container_name: agorascan
    ports:
      - "3333:3333"
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../chain/node1/el:/el
      - ../config/cl:/config
      - ../config/scan:/app/config
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
