version: '3.3'
services:
  agorascan:
    platform: linux/amd64
    image: bosagora/agora-scan:agora
    container_name: agorascan
    ports:
      - '3333:3333'
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../chain/node1/el:/el
      - ../config/cl:/config
      - ../config/scan:/app/config
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
